spring:
  application:
    name: productapi

server:
    version: 1.2

springdoc:
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic